CREATE DATABASE AACBusiness;
GO
USE AACBusiness;
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AAC_USERS](
	[UserId] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](100) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[LastLogin] [datetime] NULL,
 CONSTRAINT [PK_AAC_USERS] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


INSERT INTO [dbo].[AAC_USERS] (Username, Password, LastLogin) VALUES ('zzeddy', CONVERT(VARCHAR(32), HASHBYTES('MD5', '1234'),2) , CURRENT_TIMESTAMP)
INSERT INTO [dbo].[AAC_USERS] (Username, Password, LastLogin) VALUES ('deutan', CONVERT(VARCHAR(32), HASHBYTES('MD5', '1234'),2) , CURRENT_TIMESTAMP)
INSERT INTO [dbo].[AAC_USERS] (Username, Password, LastLogin) VALUES ('shramp', CONVERT(VARCHAR(32), HASHBYTES('MD5', '1234'),2) , CURRENT_TIMESTAMP)
