INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Apple');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rice');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Archeum Ore');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Cornflower');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Starshard Ingot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Copper Ore');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Bamboo Stalk');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Chicken Meat');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Oats');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Millet');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lily');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Blueberry');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pomegranate');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Avocado');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Egg');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lavender');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rosemary');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Vanilla');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Cactus');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Narcissus');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lotus');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Bay Leaf');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Cultivated Ginseng');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Azalea');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Clover');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rose');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Hay Bale');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Iris');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Hereafter Stone');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pork');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Potato');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Yam');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Carrot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Peanut');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Garlic');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Wheat');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Barley');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Strawberry');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pelt');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Raw Stone');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Cucumber');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Corn');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Bean');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Tomato');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Log');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pepper');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Iron Ore');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Silver Ore');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Gold Ore');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Beechnut');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Jujube');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Acorn');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lemon');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fig');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Beef');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Coconut');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Wool');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Olive');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Milk');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Grape');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Diamond');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ruby');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sapphire');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Amethyst');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Anya Pebble');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pure Iron Ore');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Emerald');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pearl');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Topaz');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pure Silver Ore');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pure Gold Ore');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fabric');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Iron Ingot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sturdy Ingot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Copper Ingot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Glossy Feather');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lumber');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Stone Brick');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Cotton');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Tangy Soda');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Vegetable Soup');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sweet Soup');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Enhanced Glider Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ultimate Glider Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Banana');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Orange');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Cherry');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mint');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mushroom');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Thistle');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Wild Ginseng');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Beguiling Wave Lunadrop');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rye');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Glowing Prism');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Anya Ingot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Clockwork Cat Chest');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Cactus Seed');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Narcissus Seed');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Iris Seed');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Thunderstruck Tree');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Natural Rubber');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Bamboo Shoot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Moringa Fruit');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Regrade Brazier');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Organic Fertilizer');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Livestock Supplement');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Chili Pepper');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Aloe');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fine Lumber');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sunridge Ingot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Nuri Forest Lumber');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Leather');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fine Leather');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Wind Spirit Leather');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Beautifully Colored Fabric');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Cloudspun Fabric');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sunlight Archeum Dust');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Moonlight Archeum Dust');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Starlight Archeum Dust');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sunlight Archeum Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Moonlight Archeum Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Starlight Archeum Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sunlight Archeum Crystal');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Moonlight Archeum Crystal');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Starlight Archeum Crystal');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sunlight Archeum Essence');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Moonlight Archeum Essence');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Starlight Archeum Essence');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Spacious Storage Chest');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Vegetable Bread');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sweet Bread');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Shining Vein Seed');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pure Archeum Ore');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Silver Ingot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Gold Ingot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Archeum Ingot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Delphinad Wave Ring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Archeum Log');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Aquafarm Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Flaming Log');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Deluxe Sandwich');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Simple Sandwich');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Delphinad Earth Earring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Delphinad Wave Earring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pearl Oyster');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Red Coral');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Green Coral');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Antler Coral');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'White Coral');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Blue Coral');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Orange Coral');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Yellow Coral');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Abalone');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Penshell');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Seabreeze Essence');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Recovery Pouch');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Kraken''s Might');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Desert Fire');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Nui''s Nova');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Black Pearl');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Reckless Captain''s Cuirass');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Reckless Captain''s Vambraces');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Reckless Captain''s Gauntlets');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Reckless Captain''s Greaves');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Reckless Captain''s Sabatons');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Small Leaf Pigment');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Scented Petal Pigment');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Viscous Glossy Oil');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Emulsified Oil');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Deeply Colored Oil');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rough Polish');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Non-Stick Polish');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rainbow Polish');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Small Root Pigment');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Small Seed Oil');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Opaque Polish');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Strong Wheel');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'High Power Engine');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Duck Down');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Goose Down');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Goat Wool');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Epherium Wave Bow');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Epherium Flame Guards');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Thatched Farmhouse Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Tudor Slate Cottage Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rustic Slate Cottage Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rustic Rose Cottage Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Tudor Rose Cottage Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Vita Root');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Thundering Footfalls');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Little Demon''s Toy');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'BloodCrimson Lightning');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Knotted Hell Shirt');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Secret Transformation Breeches');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Silent Forest Fists');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Glory of Pavitra the Conqueror');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mysterious Garden Powder');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Design Fragment: Growling Yawl');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Treasure Map with Coordinates');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Beguiling Flaming Gale Lunadrop');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Beguiling Tidal Gale Lunadrop');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Beguiling Lively Wave Lunadrop');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lunarite');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Superior Lunarite');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Prime Lunarite');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Heat of Eternal Summer');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Eternal Winter Chill');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Heavy Sconce');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Monarch''s Spacious Bed');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sweet Candy');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rice Seed Bundle');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Eco-Friendly Fuel');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Yata Meat');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Axis Mundi Aegis');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Combined Feed');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Book of Auroria');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lord''s Coin');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Abundant Health Beverage Table');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ample Mana Appetizer Table');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Bait Worm');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pike');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Eel');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sea Bass');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Rainbow Trout');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'The Art of Language');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Paper');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Grimghast Cuirass');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Grimghast Vambraces');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Grimghast Sabatons');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Chopped Squid');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Chopped Roosterfish');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Chopped Pike');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Basic Fishing Line');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Reinforced Fishing Line');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Wrapped Bamboo Fishing Rod');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Handicraft Yarn');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fragrant Soup');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Building Management Title');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dawn Lake Light Essence');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Alloy Combiner');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Resplendent Weapon Regrade Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Resplendent Armor Regrade Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Weapon Regrade Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Armor Regrade Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucky Sunpoint');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sunpoint');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Moonpoint');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sunpoint Fragment');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Blank Regrade Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucky Moonpoint');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Labyrinth''s Leather Armor Chest');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Labyrinth''s Plate Armor Chest');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Elite Merchant''s Cushion');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Acorn Beehive');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Honey');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Smoke Bead');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Golden Teardrop Storage Chest');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Red Dragon Spinal Ridge');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Arcadian Seafoam');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Swirling Whirlpool');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Abyssal Armory Chest');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Scarlet Peacock Butterfly');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dahuta''s Bubble');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Hearty Soup');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Bear Fur');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Caernord Zephyr Triangular Rig');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Radiant Gale Lunagem: Mastery');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Radiant Earth Lunagem: Flexibility');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Radiant Earth Lunagem: Mastery');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Radiant Gale Lunagem: Fidelity');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Meina''s Feathered Cap');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Meina''s Jerkin');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Meina''s Breeches');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Meina''s Guards');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Meina''s Belt');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Glenn''s Pants');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Raging Lionheart Figurehead');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Chopped Produce');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Orchard Puree');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dried Flowers');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ground Spices');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ground Grain');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Medicinal Powder');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Trimmed Meat');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucid Gale Lunagem: Mastery');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucid Gale Lunagem: Fury');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucid Gale Lunagem: Serenity');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucid Gale Lunagem: Wrath');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucid Gale Lunagem: Harbinger');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucid Gale Lunagem: Torrent');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucid Earth Lunagem: Finesse');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fire Lunarite');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fine Fire Lunarite');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Superior Fire Lunarite');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Wave Lunarite');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fine Wave Lunarite');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Superior Wave Lunarite');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Gale Lunarite: Pierce');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Gale Lunarite: Torrent');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Superior Gale Lunarite: Pierce');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Superior Gale Lunarite: Torrent');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fine Gale Lunarite: Pierce');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fine Gale Lunarite: Torrent');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Earth Lunarite: Celerity');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Earth Lunarite: Impenetrable');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Superior Earth Lunarite: Finesse');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fine Earth Lunarite: Celerity');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fine Earth Lunarite: Impenetrable');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ayanad Earth Scepter');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ayanad Wave Bow');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sparkling Shell Dust');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Magnificent Flame Earring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Magnificent Wave Earring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Epherium Earth Earring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Epherium Flame Earring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Epherium Wave Earring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ayanad Life Ring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ayanad Scroll: 3rd Floor Lobby');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mossy Pool');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fortuna Die');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Valau Rune');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Zena Rune');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Prismatic Pearl');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Prismatic Diamond');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Tax Certificate');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Resplendent Accessory Regrade Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Accessory Regrade Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Starpoint');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucky Starpoint');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sunset Haze Greatclub');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Recollections Sash');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Unique Regrade Charm');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Earthmana Leaf');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fresh Fertilizer');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Multi-Purpose Aging Larder');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Charcoal Stabilizer');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dragon Essence Stabilizer');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Draught of Forgiveness');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucid Earth Lunagem: Mastery');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pine Woodlot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sheep Pen');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dairy Pen');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Super Weapon Temper');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Super Armor Temper');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Tyrenos''s Index');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dazzling Heroic Regrade Charm');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dazzling Arcane Regrade Charm');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Dagger');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Nodachi');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Staff');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Bow');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Flute');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Vexed Desire');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Malevolent Obsidian');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Haunted Obsidian');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Tainted Jewel');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ritual Aquamarine');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sulfur Crystal');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mercury Solution');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Brine Flakes');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dense Lead');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Renaia''s Research Journal');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Herzan''s Research');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Inakos''s Grimoire');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ruthart''s Doodles');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Weathered Beryl');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Philosopher''s Stone Fragment');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Pygmy Skull');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ouroboros Statue');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Kaylin''s Quill');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Stena''s Crystal Orb');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Runert''s Carving Knife');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Jergant''s Music Box');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Tinnereph''s Monocle');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Wynn''s Bronze Cross');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Halnaak''s Golden Scale');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Alexander''s Platinum Case');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Vyrava''s Inferno');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Jola''s Scale');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Iron Armor Fragment');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Garden Records');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Anthalon''s Crimson Hallow');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Fierce Vow''s Blood');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Improved Skyreach Woodlot');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dawnsdrop Fists');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Enchanted Blueprint');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Elixir of Insatiable Greed');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ship Component Regrade Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Growling Zephyr Square Foresail');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Growling Zephyr Square Mainsail');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Radiant Archeum Tree Sapling');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sharpwind Mining Drill');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Illustrious Vocational Hood');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Illustrious Vocational Gloves');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Delphinad Lightning Necklace');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Hood');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Shirt');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Gloves');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Cap');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Jerkin');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Fists');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Obsidian Boots');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ominous Obsidian Jerkin');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Silent Evanescence Fists');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Caernord Sea Serpent Propellant');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Possessed Topaz');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Bone Chip');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Forbidden Spellgem');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Shadow Orb');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Shatigon''s Sand');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mistral Underwater Breathing Device Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mistral Mast Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Seastorm Mast Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Captain''s Cannon Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Shrapnel Cannon Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Naval Cannon Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Large-Caliber Cannon Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'High-Angle Siege Cannon Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'High-Speed Siege Cannon Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Chain-Shot Cannon Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Beast Figurehead Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Charred Bonekraal Figurehead Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Raging Lionheart Figurehead Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ivory Nui Figurehead Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sea Drake Figurehead Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Caernord Sea Serpent Propellant Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mistral Trade Pack Storage Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Seastorm Trade Pack Storage Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lutesong Mistral Rudder Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lutesong Seastorm Rudder Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Austeran Mistral Rudder Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Caernord Mistral Rudder Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mistral Compass Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mistral Shroudlight Design');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Language Proficiency Spellbook');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Enoan Galleon Blueprint Fragment');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Sirensong Fishing Boat Propellant');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Grinding Guardian Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Superior Grinding Guardian Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Red Regrade Charm');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Shroudmaster Ring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Shroudmaster Earring');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Andelph Fishing Boat Propellant');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'One-Hander Metal Mana Wisp');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Two-Hander Metal Mana Wisp');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Wooden Mana Wisp');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Musical Mana Wisp');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Large Jewelry Mana Wisp');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Small Jewelry Mana Wisp');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Cloth Mana Wisp');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Leather Mana Wisp');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Plate Mana Wisp');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Design: Sirensong Mistral Rudder');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Vivid Gale Lunascale: Tempest');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Vivid Gale Lunascale: Pierce');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Gilda Dust');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Thunderstruck Log');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Glider Manacharge Scrolls');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Healing Grimoire');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Prime Weapon Temper');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Epherium Lotus Fence Pillar');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Jujube Juice');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Jujube Sparkling Wine');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Mistsong Grinding Guardian Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucky Starpoint Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Superior Gale Lunarite: Clash');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ayanad Weaponsmithing Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ayanad Armorsmithing Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ayanad Accessory Scroll');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Clear Synthium Stone');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Vivid Synthium Stone');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Radiant Synthium Stone');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Lucid Synthium Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Clear Synthium Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Wrathsmite Armor Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Kadum''s Bark');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Misagon''s Crystal');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Bound Serendipity Stone');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Farm Freighter Upgrade Ticket');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ayanad Scroll Scrap');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Spellbook: Unstoppable Will');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Kingdom''s Shadow');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Dawn of Glory');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Assorted Ribs');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Scented Leaf');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Royal Seed');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Heavy Hardwood');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Brinebound Rock');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Ground Fish Chum');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Celestial Weapon Anchoring Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Celestial Armor Anchoring Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Divine Armor Anchoring Shard');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Glittering Charcoal Milk');
INSERT INTO [dbo].[AAC_ITEMS] ([Name]) VALUES (N'Schematic Scrap');